name: Test on PR
on: [push]
# pull_request:
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: |
          echo "ğŸ‰ The job was automatically triggered by an event."
      - name: Publish test artifacts
        run: |
          echo "ğŸ‰ The job was automatically triggered by an event."
